# .github/workflows/native-rust.yml
name: native-rust
on:
  push:
  workflow_dispatch:

jobs:
  build-test-smoke:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Ensure Rust is available for pyo3 builds
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install maturin numpy jsonschema pyyaml

      # ✅ Build a wheel and pip install it (no venv needed)
      - name: Build + install native wheel
        working-directory: hu_solver/native
        run: |
          maturin build --release -i python3.11 --out dist
          pip install --force-reinstall dist/*.whl
          python - <<'PY'
          import hu_solver_native, sys
          print("Built:", hu_solver_native.__name__)
          print("Location:", hu_solver_native.__file__)
          PY

      - name: Run unit tests
        run: |
          python -m hu_solver.tests.test_determinism
          python -m hu_solver.tests.test_schema_validation
          python -m hu_solver.toy.kuhn

      - name: Produce smoke policy
        run: |
          python - <<'PY'
          from hu_solver.solver import Solver
          s = Solver("hu_solver/configs/hu_100bb.yaml")
          s.train(iters=200_000, out_dir="policies/hu_100bb_v1_smoke")
          PY

      - name: Upload smoke artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hu_100bb_v1_smoke
          path: policies/hu_100bb_v1_smoke/**
